apiVersion: v1
kind: Pod
metadata:
  labels:
    project: practice
    author: Abdumalik
  name: busybox
  namespace: a-nabixojayev
spec:
  containers:
    - command:
        - sleep 3600
      image: busybox
      name: busybox
